package com.minutemart.quickcommerce.identity.domain;

public enum IdentityError {
    INVALID_PHONE_NUMBER,
    IDENTITY_NOT_FOUND,
    IDENTITY_BLOCKED,
    IDENTITY_DELETED,
    OTP_CHALLENGE_NOT_FOUND,
    OTP_EXPIRED,
    OTP_INVALID,
    OTP_ATTEMPTS_EXCEEDED,
    OTP_RESEND_TOO_SOON,
    ROLE_ALREADY_ASSIGNED,
    ROLE_NOT_ACTIVE,
    ROLE_SELECTION_REQUIRED,
    INVALID_ROLE_SCOPE,
    INVALID_CLIENT_APPLICATION,
    INVALID_INVITATION_ROLE,
    SESSION_INVALID,
    REFRESH_TOKEN_INVALID,
    INVALID_CREDENTIALS,
    PASSWORD_NOT_SET,
    INVITATION_NOT_FOUND,
    INVITATION_EXPIRED,
    INVITATION_ALREADY_ACCEPTED,
    INVITATION_REVOKED,
    CREDENTIALS_ALREADY_SET
}
